-- Build 41 baseline: preserves Build 40 table and column order.

CREATE TABLE quotes (
                    token TEXT PRIMARY KEY, owner TEXT NOT NULL, expires BIGINT NOT NULL,
                    payload TEXT NOT NULL, ride_id TEXT);

CREATE TABLE rides (
                    id TEXT PRIMARY KEY, owner TEXT NOT NULL, payload TEXT NOT NULL);

CREATE TABLE events (
                    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ride_id TEXT NOT NULL,
                    at_ms BIGINT NOT NULL, actor TEXT NOT NULL, type TEXT NOT NULL,
                    payload TEXT NOT NULL);

CREATE TABLE passengers (
                    id TEXT PRIMARY KEY, phone TEXT NOT NULL UNIQUE, first_name TEXT NOT NULL DEFAULT '',
                    last_name TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', created_ms BIGINT NOT NULL,
                    updated_ms BIGINT NOT NULL);

CREATE TABLE otp_challenges (
                    id TEXT PRIMARY KEY, phone TEXT NOT NULL, code_hash TEXT NOT NULL, created_ms BIGINT NOT NULL,
                    expires_ms BIGINT NOT NULL, attempts BIGINT NOT NULL DEFAULT 0, consumed_ms BIGINT);

CREATE TABLE auth_sessions (
                    id TEXT PRIMARY KEY, passenger_id TEXT NOT NULL, access_hash TEXT NOT NULL UNIQUE,
                    access_expires_ms BIGINT NOT NULL, refresh_hash TEXT NOT NULL UNIQUE,
                    refresh_expires_ms BIGINT NOT NULL, revoked_ms BIGINT,
                    FOREIGN KEY(passenger_id) REFERENCES passengers(id));

CREATE TABLE saved_places (
                    passenger_id TEXT NOT NULL, slot TEXT NOT NULL, payload TEXT NOT NULL,
                    updated_ms BIGINT NOT NULL, PRIMARY KEY(passenger_id, slot),
                    FOREIGN KEY(passenger_id) REFERENCES passengers(id));

CREATE TABLE recent_destinations (
                    passenger_id TEXT NOT NULL, identity TEXT NOT NULL, payload TEXT NOT NULL,
                    used_ms BIGINT NOT NULL, PRIMARY KEY(passenger_id, identity),
                    FOREIGN KEY(passenger_id) REFERENCES passengers(id));

CREATE TABLE payment_methods (
                    id TEXT PRIMARY KEY, passenger_id TEXT NOT NULL, type TEXT NOT NULL,
                    brand TEXT NOT NULL, last4 TEXT NOT NULL, expiry_month BIGINT NOT NULL,
                    expiry_year BIGINT NOT NULL, is_default BIGINT NOT NULL DEFAULT 0,
                    created_ms BIGINT NOT NULL,
                    FOREIGN KEY(passenger_id) REFERENCES passengers(id));

CREATE TABLE driver_state (
                    id BIGINT PRIMARY KEY CHECK(id=1), online BIGINT NOT NULL DEFAULT 0,
                    name TEXT NOT NULL DEFAULT 'Development driver',
                    vehicle TEXT NOT NULL DEFAULT 'Test vehicle', plate TEXT NOT NULL DEFAULT 'DEMO');

CREATE TABLE driver_declines (
                    ride_id TEXT PRIMARY KEY, until_ms BIGINT NOT NULL);

CREATE TABLE driver_presence (
                    id BIGINT PRIMARY KEY CHECK(id=1), latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL,
                    recorded_ms BIGINT NOT NULL);

CREATE TABLE driver_offer_state (
                    id BIGINT PRIMARY KEY CHECK(id=1), ride_id TEXT NOT NULL, expires_ms BIGINT NOT NULL);

CREATE TABLE development_earnings (
                    ride_id TEXT PRIMARY KEY, completed_ms BIGINT NOT NULL,
                    fare_subtotal_cents BIGINT NOT NULL, gst_cents BIGINT NOT NULL,
                    passenger_total_cents BIGINT NOT NULL, platform_commission_cents BIGINT NOT NULL,
                    driver_gross_before_costs_cents BIGINT NOT NULL,
                    CHECK (fare_subtotal_cents >= 0 AND gst_cents >= 0 AND passenger_total_cents >= 0));

CREATE TABLE fleet_drivers (
                id TEXT PRIMARY KEY, name TEXT NOT NULL, vehicle TEXT NOT NULL,
                plate TEXT NOT NULL, category TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'PENDING', online BIGINT NOT NULL DEFAULT 0,
                lat DOUBLE PRECISION, lng DOUBLE PRECISION, located_ms BIGINT, created_ms BIGINT NOT NULL);

CREATE TABLE fleet_credentials (
                token_hash TEXT PRIMARY KEY, driver_id TEXT NOT NULL UNIQUE,
                FOREIGN KEY(driver_id) REFERENCES fleet_drivers(id));

CREATE TABLE fleet_offers (
                driver_id TEXT PRIMARY KEY, ride_id TEXT NOT NULL UNIQUE,
                expires_ms BIGINT NOT NULL, FOREIGN KEY(driver_id) REFERENCES fleet_drivers(id));

CREATE TABLE fleet_declines (
                driver_id TEXT NOT NULL, ride_id TEXT NOT NULL, until_ms BIGINT NOT NULL,
                PRIMARY KEY(driver_id,ride_id));

CREATE TABLE fleet_documents (
                driver_id TEXT NOT NULL, kind TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'NOT_SUBMITTED',
                expiry_date TEXT, filename TEXT, mime TEXT, content BYTEA, revision BIGINT NOT NULL DEFAULT 0, note TEXT, submitted_ms BIGINT, PRIMARY KEY(driver_id,kind));

CREATE TABLE fleet_audit (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, driver_id TEXT NOT NULL, actor TEXT NOT NULL,
                action TEXT NOT NULL, at_ms BIGINT NOT NULL);

CREATE TABLE fleet_pin_attempts (ride_id TEXT PRIMARY KEY, attempts BIGINT NOT NULL, until_ms BIGINT NOT NULL);

CREATE TABLE fleet_logins (
                    driver_id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE,
                    salt TEXT NOT NULL, password_hash TEXT NOT NULL,
                    must_reset BIGINT NOT NULL DEFAULT 0, phone TEXT);

CREATE TABLE fleet_login_attempts (
                    username TEXT PRIMARY KEY, failures BIGINT NOT NULL, until_ms BIGINT NOT NULL);

CREATE TABLE fleet_driver_eligibility (
                driver_id TEXT NOT NULL, category TEXT NOT NULL,
                source TEXT NOT NULL DEFAULT 'ADMIN', updated_ms BIGINT NOT NULL,
                PRIMARY KEY(driver_id, category));

CREATE TABLE fleet_radar (
                ride_id TEXT PRIMARY KEY, expires_ms BIGINT NOT NULL,
                status TEXT NOT NULL DEFAULT 'OPEN', created_ms BIGINT NOT NULL);

CREATE TABLE fleet_radar_candidates (
                ride_id TEXT NOT NULL, driver_id TEXT NOT NULL, distance_km DOUBLE PRECISION NOT NULL,
                PRIMARY KEY(ride_id, driver_id));

CREATE TABLE ride_feedback (
                    ride_id TEXT NOT NULL,
                    author_role TEXT NOT NULL CHECK(author_role IN ('PASSENGER','DRIVER')),
                    author_id TEXT NOT NULL,
                    target_id TEXT NOT NULL,
                    stars BIGINT NOT NULL CHECK(stars BETWEEN 1 AND 5),
                    tags_json TEXT NOT NULL,
                    comment TEXT NOT NULL,
                    created_ms BIGINT NOT NULL,
                    updated_ms BIGINT NOT NULL,
                    PRIMARY KEY(ride_id, author_role));

CREATE TABLE support_cases (
                    id TEXT PRIMARY KEY,
                    ride_id TEXT,
                    reporter_role TEXT NOT NULL CHECK(reporter_role IN ('PASSENGER','DRIVER')),
                    reporter_id TEXT NOT NULL,
                    category TEXT NOT NULL,
                    description TEXT NOT NULL,
                    status TEXT NOT NULL,
                    admin_note TEXT NOT NULL,
                    created_ms BIGINT NOT NULL,
                    updated_ms BIGINT NOT NULL);

CREATE TABLE admin_staff(
                id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE, role TEXT NOT NULL,
                salt TEXT NOT NULL, secret_hash TEXT NOT NULL, active BIGINT NOT NULL DEFAULT 1,
                created_ms BIGINT NOT NULL);

CREATE TABLE admin_sessions(
                token_hash TEXT PRIMARY KEY, staff_id TEXT NOT NULL, expires_ms BIGINT NOT NULL,
                FOREIGN KEY(staff_id) REFERENCES admin_staff(id));

CREATE TABLE admin_audit(
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, at_ms BIGINT NOT NULL, actor TEXT NOT NULL,
                action TEXT NOT NULL, subject TEXT NOT NULL);

CREATE INDEX otp_phone_created ON otp_challenges(phone, created_ms);

CREATE INDEX recent_destinations_used
                    ON recent_destinations(passenger_id, used_ms DESC);

CREATE INDEX payment_methods_passenger
                    ON payment_methods(passenger_id, is_default DESC, created_ms);

CREATE INDEX fleet_audit_driver ON fleet_audit(driver_id, id);

CREATE UNIQUE INDEX fleet_login_phone ON fleet_logins(phone) WHERE phone IS NOT NULL;

CREATE INDEX fleet_radar_driver
                ON fleet_radar_candidates(driver_id, ride_id);

CREATE INDEX feedback_target ON ride_feedback(target_id, author_role);

CREATE INDEX cases_reporter ON support_cases(reporter_role, reporter_id, created_ms DESC);

CREATE INDEX cases_status ON support_cases(status, updated_ms DESC);

CREATE INDEX admin_audit_time ON admin_audit(at_ms DESC);
