"""Generate the initial PostgreSQL schema from the accepted SQLite schema.
Only used to create 001 once; never regenerate an applied migration.
"""
import os
import re
import sqlite3
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from server import Service
from staff38 import Staff


def generate():
    os.environ.pop('RIDENOVA_OWNER_USERNAME', None)
    os.environ.pop('RIDENOVA_OWNER_PASSWORD', None)
    with tempfile.TemporaryDirectory() as temp:
        database = str(Path(temp) / 'schema.sqlite3')
        Service(database)
        Staff(database)
        with sqlite3.connect(database) as db:
            rows = db.execute("SELECT sql FROM sqlite_master WHERE sql IS NOT NULL "
                              "AND name NOT LIKE 'sqlite_%' ORDER BY type DESC, rowid").fetchall()
        output = ['-- Build 41 baseline: preserves Build 40 table and column order.']
        for (sql,) in rows:
            sql = re.sub(r'INTEGER PRIMARY KEY AUTOINCREMENT', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', sql, flags=re.I)
            sql = re.sub(r'\bINTEGER\b', 'BIGINT', sql, flags=re.I)
            sql = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', sql, flags=re.I)
            sql = re.sub(r'\bBLOB\b', 'BYTEA', sql, flags=re.I)
            output.append(sql + ';')
        target = ROOT / 'migrations/001_build40_baseline.sql'
        target.parent.mkdir(exist_ok=True)
        if target.exists():
            raise RuntimeError('Refusing to overwrite immutable migration')
        target.write_text('\n\n'.join(output) + '\n', encoding='utf-8')


if __name__ == '__main__': generate()
